name: Workflow
on:
  push:
    branches: [master]
  pull_request:
      branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Backend
      #- name: Checkout repository
      #  uses: actions/checkout@v4

      #- name: Setup Java
      #  uses: actions/setup-java@v4
      #  with:
      #    distribution: 'temurin'
      #    java-version: '17'
      #    cache: 'maven'
  
      #- name: Validate, compile, test and package maven project
      #  run: mvn -B package --file ./backend/pom.xml

      # Frontend

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i

      - name: Run tests
        run: npm test
